# Site settings
title: Displaced
email: nauras@moogmedia.ca
description: Displaced description
baseurl: "/"
url: "www.displacedseries.com"
github_username:  timelytree
include: ["_pages"]
permalink: /:title

collections:
  category:
    output: true

# Build settings
markdown: kramdown

sass:
  sass_dir: _scss
